- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/main/java/com/github/fridujo/rabbitmq/mock/Receiver.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ExtensionTest.java
> Add queue length limit support using x-args

- src/main/java/com/github/fridujo/rabbitmq/mock/AmqArguments.java
- src/main/java/com/github/fridujo/rabbitmq/mock/ConsumerWrapper.java
- src/main/java/com/github/fridujo/rabbitmq/mock/Message.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MessageComparator.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/main/java/com/github/fridujo/rabbitmq/mock/Receiver.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/BindableMockExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockDirectExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockExchangeFactory.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockFanoutExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockHeadersExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockTopicExchange.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ExtensionTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/exchange/ExchangeTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/tool/ClassesTest.java
> Priority queues support

- pom.xml
- src/it/spring_boot/pom.xml
**amqp-client** to 5.4.2
Add integration test run with **Spring-Boot** 2.1.0.M4
> Upgrade versions

- .travis.yml
- src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockDefaultExchange.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ChannelTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/MetricsCollectorTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/MockConnectionTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/exchange/ExchangeTest.java
> Fix default exchange name when publising from it

- pom.xml
- src/it/spring_cloud_bus/pom.xml
- src/it/spring_cloud_bus/src/main/java/com/github/fridujo/rabbitmq/mock/integration/springcloudbus/ConfigClient.java
- src/it/spring_cloud_bus/src/test/java/com/github/fridujo/rabbitmq/mock/integration/springcloudbus/ConfigClientTest.java
- src/it/spring_cloud_bus/src/test/java/com/github/fridujo/rabbitmq/mock/integration/springcloudbus/ConfigClientTestConfiguration.java
- src/it/spring_cloud_bus/src/test/java/com/github/fridujo/rabbitmq/mock/integration/springcloudbus/ConfigServerValues.java
- src/it/spring_cloud_bus/src/test/java/com/github/fridujo/rabbitmq/mock/integration/springcloudbus/ContextRefreshLock.java
- src/it/spring_cloud_bus/src/test/java/com/github/fridujo/rabbitmq/mock/integration/springcloudbus/LoggingHttpInterceptor.java
- src/it/spring_cloud_bus/src/test/resources/META-INF/spring.factories
- src/it/spring_cloud_bus/src/test/resources/logback-test.xml
> Add integration test with Spring Cloud Bus

- README.md
- pom.xml
- src/it/spring_boot/pom.xml
- src/it/spring_cloud_bus/pom.xml
- src/main/java/com/github/fridujo/rabbitmq/mock/AmqpExceptions.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/BindableMockExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockDefaultExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockDirectExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockExchangeFactory.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockFanoutExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockHeadersExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockTopicExchange.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ChannelTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/exchange/FixDelayExchangeCreator.java
Fixes #34.
See http://www.rabbitmq.com/amqp-0-9-1-quickref.html#exchange.declare
> Make exchange declare idempotent

- pom.xml
- src/it/spring_boot/src/main/java/com/github/fridujo/rabbitmq/mock/integration/springboot/AmqpApplication.java
> Add IT for raw channel uses with Spring-Boot 1.5.12

- src/main/java/com/github/fridujo/rabbitmq/mock/Message.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/test/java/com/github/fridujo/rabbitmq/mock/IntegrationTest.java
> mark redelivered messages

- src/it/alpakka/pom.xml
- src/it/alpakka/src/test/scala/com/github/fridujo/rabbitmq/mock/integration/alpakka/scala/TestSuite.scala
- src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockConnection.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ComplexUseCasesTests.java
> Fix consumer cancelation when another connection was closed

- pom.xml
> Skip Integration Tests when tests are

- src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ChannelTest.java
> Fix transactional channel to support multiple commits after a single select

- CONTRIBUTING.md
- pom.xml
Do not download half of the universe when running the maven-invoker-plugin
> Do not define local repo for Maven dependencies for maven-invoker-plugin

- src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/main/java/com/github/fridujo/rabbitmq/mock/Receiver.java
- src/main/java/com/github/fridujo/rabbitmq/mock/Transaction.java
- src/main/java/com/github/fridujo/rabbitmq/mock/TransactionalOperations.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/BindableMockExchange.java
- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockDefaultExchange.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ChannelTest.java
- src/test/java/com/github/fridujo/rabbitmq/mock/exchange/FixDelayExchange.java
Change-Id: I230ab88df99b665c47329caa6e8c89ba1af016cf
> 91: Add support for mandatory flag. Make sure it works for RpcClient

- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ComplexUseCasesTests.java
> Requeue unacked messages delivered to a consumer when it is cancelled

- src/main/java/com/github/fridujo/rabbitmq/mock/MockChannel.java
- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
- src/test/java/com/github/fridujo/rabbitmq/mock/ChannelTest.java
> Give access to mock queues & their messages

- src/it/alpakka/pom.xml
- src/it/alpakka/src/test/scala/com/github/fridujo/rabbitmq/mock/integration/alpakka/scala/TestSuite.scala
Upgrading to Alpakka 2.0.
This integration test is randomly failing.
With the hope that this upgrade will fix this.
> Upgrade Alpakka version and hoping for stability

- src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockTopicExchange.java
- src/test/java/com/github/fridujo/rabbitmq/mock/exchange/ExchangeTest.java
> Fix routing key with # matching for topic exchange

- README.md
- pom.xml
* amqp-client -> 5.9.0
* upgrade spring-boot 2.2.X IT to 2.2.8 (latest)
* added an IT for spring-boot 2.3.X
> Upgrade amqp-client & spring-boot ITs

- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
I didn't add a test for this as nothing functionally changed and is hard to test threading issues.
Let me know if you think that is acceptable or not.
Suffice to say, `LinkedHashMap` is not safe to use by multiple threads (`PriorityBlockingQueue`, the other structure used in `MockQueue`, is though)
> Synchronize access to thread unsafe maps in MockQueue

- src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java
Tests were failing.
I didn't run any tests when I submitted this code -- guess I've been to used to tests running when a PR is submitted.  All tests pass with this fix.
> Fix for regression introduced by #318
